version: '3.4'

services:
  amr.reportsmicroservice:
    image: ${DOCKER_REGISTRY-}amrreportsmicroservice
    build:
      context: .
      dockerfile: reports-microservice/src/AMR.ReportsMicroservice/Dockerfile

  amr.salesmicroservice:
    image: ${DOCKER_REGISTRY-}amrsalesmicroservice
    build:
      context: .
      dockerfile: sales-microservice/src/AMR.SalesMicroservice/Dockerfile

